services:
  # compose.yaml
  influxdb3-core:
    container_name: influxdb3-core
    image: influxdb:3-core
    ports:
      - 8181:8181
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --plugin-dir=/var/lib/influxdb3/plugins
    volumes:
      - type: bind
        source: /home/pietrocouto/.influxdb3/core/data
        target: /var/lib/influxdb3/data
      - type: bind
        source: /home/pietrocouto/.influxdb3/core/plugins
        target: /var/lib/influxdb3/plugins
  influxdb3-explorer:
    image: influxdata/influxdb3-ui:1.2.0
    container_name: influxdb3-explorer
    ports:
      - "8888:80"
    # opcional: modo admin habilita gestão de DB, tokens, plugins
    command: ["--mode=admin"]
    restart: unless-stopped
  # chronograf:
  #   image: chronograf:latest
  #   ports:
  #     - '127.0.0.1:8888:8888'
  #   volumes:
  #     - chronograf-storage:/var/lib/chronograf
  #   depends_on:
  #     - influxdb
  #   environment:
  #     - INFLUXDB_URL=http://influxdb:8086
  #     - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
  #     - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
  # grafana:
  #   image: grafana/grafana:latest
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - grafana-storage:/var/lib/grafana
  #     - ./grafana-provisioning/:/etc/grafana/provisioning
  #   depends_on:
  #     - influxdb
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
  #     - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
volumes:
  influxdb-storage: